# Generated by Django 5.2.8 on 2025-11-25 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='timestamp',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='proforma_file',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='purchase_order_file',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='receipt_file',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('pending_l1', 'Pending L1'), ('rejected_l1', 'Rejected L1'), ('pending_l2', 'Pending L2'), ('rejected_l2', 'Rejected L2'), ('approved', 'Approved'), ('ordered', 'Ordered'), ('delivered', 'Delivered'), ('completed', 'Completed')], default='pending_l1', max_length=20),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='requests.purchaserequest')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('received', 'Received'), ('partially_received', 'Partially Received'), ('not_received', 'Not Received')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('finance_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('purchase_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_validation', to='requests.purchaserequest')),
            ],
        ),
    ]
