# Generated by Django 5.2.8 on 2025-11-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_alter_approval_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='proforma_file',
            field=models.FileField(blank=True, null=True, upload_to='proformas/'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='urgency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
